=head0 Preface

=head1 Background

I<SimpleMedia Direct Layer> is a cross-platform C library that provides access
to several input and output devices. Most popularly it is used for its access
to the 2D video framebuffer and inputs for games. 

In addition to the core libsdl there are several other libraries that provide many
features such as I<Text>, I<Mixers>, I<Images> and I<GFX>.

SDL Perl binds several of these libraries as closely as possible in the C<SDL::*> namespace.
Moreover SDL Perl provides several high level libraries in the C<SDLx::*> namespace.

=head1 Audience

This book is written for new users of SDL Perl who have done some Perl. It is not necessary
for the audience to be aware SDL internals, as this book covers most areas as it goes.

=head1 Format of this book

This book will be formated into chapters that progressively increase in topics and complexity. However
each chapter can be treated as separate tutorials to jump to and learn.

Each chapter will have a specific task (i.e. I<Making Pong>), which we will work towards. The source
for each chapter will be broken up and exaplained. Sources and data files will be provided on L<http://sdl.perl.org>.

Finally the chapters will end with a exercise the reader can try out.

=head1 Purpose of this book

This book is intended to introduce game development to Perl programmers and at the same time introduce Modern Perl
through game development. The book will aim to provide simple to intermediate examples and provide suggestions for more
advanced endeavours.

=head1 Installing SDL Perl

Depending on your platform you may need some dependencies. Then we can do a final CPAN install.
 
=head2 Windows

C<Alien::SDL> will install binaries for 32bit and 64bit so there is no need to compile anything.

=head2 MacOSX

=head3 Packages

Fink has packages for SDL Perl available. However Pango is not currently supported.

=head3 Or Compiling Dependencies

C<Alien::SDL> will compile SDL dependencies from scratch with no problems as long some prerequisites are installed. C<libfreetype6>, C<libX11>, C<libvorbis>, C<libogg> and C<libpng> headers will suffice for most examples in this book.

=head2 Linux

=head3 Packages

You can use your package maintainers packages:

    sudo apt-get install libsdl-net1.2-dev libsdl-mixer1.2-dev \
    libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev \ 
    libsdl-gfx1.2-dev libsdl-pango-dev

=head3 Or Compiling Dependencies

To compile from scratch some Header Packages are required.

    sudo apt-get install build-essential xorg-dev libx11-dev \
    libpango1.0-dev libfreetype6-dev libvorbis-dev libpng12-dev \
    libogg-dev

=head2 CPAN install 

    sudo cpan SDL

For most platforms a CPAN install will suffice. Supported and tested platforms are displayed at U<http://pass.cpantesters.org/distro/S/SDL.html>.

=head1 Contact

Hopefully this book shows you areas where SDL Perl can be improved, Or you may need help with some issues. Please 
contact us with one of the following methods:

=head2 Internet

SDL Perl's homepage is at U<http://sdl.perl.org/>.

=head2 IRC

The X<IRC> channel C<#sdl> on C<irc.perl.net> is very active and a great resource for help and getting involved.

=head2 Mailing lists

If you need help with SDL Perl, send an X<email> to C<sdl-devel@perl.org>.

=head1 Examples

The code examples in this books are provided on U<http://github.com/kthakore/SDL_Manual/tree/master/code_listings> .

=head1 Acknowledgements

Perl community on C<#sdl> and C<#perl>.

