=head0 The Screen

=head1 Background

SDL manages a single screen which is attached to the video device.  The screen may contain one or more Surfaces of different kinds. But we'll leave that issue till later.  This screen is typically created using the X<SDLx::App> class.

=begin programlisting

    use strict;
    use warnings;
    use SDL;
    use SDLx::App;

    my $app = SDLx::App->new();

    sleep( 2 );

=end programlisting

The above code causes a window to appear on the desktop with nothing in it. Most current systems will fill it with a default black screen as shown. For some systems, however,
a transparent window will might be shown.  It is a good idea to ensure what we intend to display is shown. So we update the C<$app> to ensure that.

=begin programlisting

    $app->update();

=end programlisting

=head1 C<SDLx::App> Options

C<SDLx::App> also allows you to specify several options for your application.

=head2 Dimensions

First are the physical dimensions of the screen itself. Lets make the screen a square size of 400×400. Change the initialization line to:

=begin programlisting

    my $app = SDLx::App->new( width => 400, height => 400 );

=end programlisting

=head2 Title

You will notice that the window's title is either blank or on some window managers it displays the path to the script file, depending on your operating system. Suppose we want a title for a new Pong clone game:

=begin programlisting

    my $app = SDLx::App->new( width  => 400,
                              height => 400,
                              title  => 'Ping - A clone' );

=end programlisting

At this point your screen will be:

=for figure
       \includegraphics[width=0.5\textwidth]{../src/images/first.png}
        \caption{Your first SDL screen!}
         \label{fig:first_screen}

=for vim: spell

=head2 Shortcuts

There are short-hand versions of the parameter names used in the call to C<new()>.  The parameters C<width>, C<height>, and C<title> may be abbreviated as C<w>, C<h> and C<t> respectively.  So, the previous example could be written like this:

=begin programlisting

    my $app = SDLx::App->new( w => 400,
                              h => 400,
                              t => 'Ping - A clone' );

=end programlisting
