=head0 The Game Loop 

=head1 Simplest Game Loop

=for programlisting

    while($quit)
    {
       do_events();
       calculate_next_positions();
       render();
    }

=for programlisting

=head2 Problems

=head1 Fixed FPS

=head2 Problems

=head1 Variable FPS

=head2 Problems

=head1 Integrating Physics

=head2 Problems

=head1 Learn More

=for vim: spell
