=head0 Sound and Music

=head1 Streaming Music

Games need background music to set the mood. 

=head2 Audio Specs

Defining how the music will run.

=head2 Example

Lets make some noise.

=head1 Sound FX

Well we want Sound events.

=head2 Triggering 

How to make the laser 'pew' in the right time.

=head2 Example

pew pew pew pew.

=head1 Modules

=head2 C<SDLx::Sound>

Simple SDL Mixer initialization.

=head2 C<SDL::Audio>

Creating music on the fly.

=head2 C<SDL::Mixer>

Full fledge music support.

=for vim: spell
