=head0 CPAN

The rest of the Perl language.

=head1 Modules

It is good to reuse code. 

=head2 MVC Method

See where the module fits, Model, View or Controller

=head3 View

SDL will do most but helper module (Clipboard) are cool to have.

=head3 Model

Storable for games that need to store stuff 

=head3 Controller

Game::Life, make some of the games in SDL!

=head1 Picking Modules

Some considerations on when to pick modules

=head2 Dependencies

What does it depend on? Hard to install?

=head2 CPAN Testers Charts

Check the CPAN tester charts, to see if it will work on your target machines.

=head3 OS breakdowns

Are the operating systems your are aiming for working?

=head3 Bug Reports

Make and See bug reports

=head1 Conculsion

CPAN use it!

=for vim: spell
