=head0 Sound and Music

Sound and Music in SDL is handled by the C<Audio> and C<SDL_Mixer> components. C<Audio> is provided with the Core SDL Library and only supports wav files. C<SDL_Mixer> supports more audio file formats and has additional features. 

Similarly to video in SDL, there are several way for perl developers to access the Sound components of SDL. For the plain C<Audio> component the C<SDL::Audio> and related modules are available. C<SDL_Mixer> is supported with th C<SDL::Mixer> module. There is currently a C<SDLx::Sound> module in the work, but not completed at the time of writing this manual. For that reason this chapter will use C<SDL::Audio> and C<SDL::Mixer>.  

=head1 Setting Up the Audio Devices

=head1 Streaming Music

Games need background music to set the mood. 

=head2 Audio Specs

Defining how the music will run.

=head2 Example

Lets make some noise.

=head1 Sound FX

Well we want Sound events.

=head2 Triggering 

How to make the laser 'pew' in the right time.

=head2 Example

pew pew pew pew.

=head1 Mixer Effects

Making a dynamic spectrograph. 

=for figure 
       \includegraphics[width=0.5\textwidth]{../src/images/spectro-1.png}      
        \caption{A Spectrogrpah of an awesome song}               
         \label{fig:spectro}   


=begin sidebar

The songs provided with this chapters code have been used by the talent authors on U<http://8bitcollective.com>. To see the individual credits of each song have a look at C<data/music/Songs>. This is truly a great site for game songs, but please give all artists their due credits. 


=end sidebar

=head1 Modules

=head2 C<SDLx::Sound>

Simple SDL Mixer initialization.

=head2 C<SDL::Audio>

Creating music on the fly.

=head2 C<SDL::Mixer>

Full fledge music support.

=for vim: spell
