=head0 Additional Modules

=head1 PDL

The Perl Data Language (PDL) is a tool aimed at a more scientifc crowd.
Accuracy is paramount and speed is the name of the game. PDL brings to
Perl fast matrix and numerical calculations. For games in most cases a
accuracy is not critical, but speed and effiency is a great concern. For
this reason we will breifly explore how to share SDL texture data between
PDL and OpenGL. 

    + use strict;
    + use warnings;
    + use SDLx::App;
    +
    + use PDL;
    +
    + my $app = SDLx::App->new(
    +                           title => 'PDL and SDL application',
    +                           width => 640, height => 480, depth => 32,
    +                           eoq => 1);




=head2 Using the Piddle

Some example here

=head2 Connecting to SDL

Connect the SDL here.

=head1 OpenGL

Perl OpenGL

=head2 Texturing

Using textures for OpenGL.

=head3 SDL surfaces as textures

Example.

=for vim: spell
