=head0 Free Resources

When developing a game, coding is unfortunately not everything.
Not by a very, very long shot. To make up (a little) for that,
below is a list of free resources you can use in your games,
either in full or simply as inspiration for your own productions, 
in case you have an artistic vein yourself.

Make sure to check the licence for the resource and use it
accordingly, giving the original author proper credit.

B<Note:> websites come and go, so if you find any of the links
broken, or know a nice free resource that's not listed here,
please let us know so we can update the list.


=head1 Art and Sprites

=over 4

=item * L<www.cgtextures.com>

=item * L<http://www.mayang.com/textures/>

=item * L<http://www.pixelpoke.com/>

=item * L<http://www.flyingyogi.com/fun/spritelib.html>

=item * L<http://www.grsites.com/archive/textures/>

=item * L<http://www.imageafter.com/>

=item * L<http://www.absolutecross.com/graphics/textures/>

=item * L<http://www.freefoto.com/>

=item * L<http://www.noctua-graphics.de>

=item * L<http://www.m3corp.com/a/download/3d_textures/pages/index.htm>

=item * L<http://reinerstileset.4players.de/englisch.html>

=item * L<http://virtualworlds.wikia.com/>

=item * L<http://lunar.lostgarden.com/labels/free%20game%20graphics.html>

=item * L<http://pdgameresources.wordpress.com/>

=item * L<http://gaminggroundzero.com>

=back


=head1 Music and Sound Effects

=over 4

=item * L<www.freesound.org>

=item * L<www.ccmixter.org>

=item * L<http://www.jamendo.com>

=item * L<http://8bc.org>

=item * L<http://www.sakari-infinity.net>

=item * L<http://www.findsounds.com>

=item * L<http://www.grsites.com/archive/sounds/>

=back


=head1 Fonts

=over 4

=item * L<http://www.acidfonts.com/>

=item * L<http://www.grsites.com/archive/fonts/>

=back


=head1 DIY

L<http://www.gamesounddesign.com/> has several tips on making game
music, including several sources for inspiration.

If you want to create 3D models, either for cutscenes or to integrate
into your game via OpenGL, there are several nice libraries out there
for you:

B<Blender> - A free 3D graphics application for modeling, texturing,
water and smoke simulations, rendering, etc. L<http://blender.org>

B<OGRE> - An open-source graphics rendering engine, used in a large number
of production projects. It can be easily integrated via Scott Lanning's
I<Ogre> Perl bindings, on CPAN. L<http://www.ogre3d.org>
